### ISSUE TITLE
bin/bash does not exist

### ISSUE THREAD

**Issue by stevengopmo** [dahlsailrunner/docker-fundamentals#7]
Hi Erik

This has been a really great course for me.  I'll probably end up watching it several more times.  I am, however, having one problem that I lack enough experience in Linux to solve.  I'm getting this error when trying to run the sql stuff

```
/usr/bin/env: 'bash\r': No such file or directory
```

This is during this command in the sql.Dockerfile
```
CMD ["/bin/bash", "entrypoint.sh"]
```

I'm sure this is something easy but I'm stumped.  Can you help?  I do see that in actual fact that folder and file (bin & bash) do exist.  But docker thinks not I guess.

**Comment by stevengopmo** [comment]
ugh, this is not the problem afterall.  My sql script does not run and so my db does not get created.  I'll dig through the logs a bit more and see if I can find what is happening.

**Comment by stevengopmo** [comment]
Sorry for all the messages.  I'm still stuck and any help would be appreciated.  The globomatics db gets created in this project, though I see no log entries for waiting or even sql getting executed.  I see now that is because the project runs 
```
            app.ApplyDatabaseSchema();
            app.PopulateDatabaseIfEmpty();
```

I guess my original question is still open.  

```
/usr/bin/env: 'bash\r': No such file or directory
```

**Comment by stevengopmo** [comment]
ah!  fixed it.  It was line endings.  I'll close this but if you do get a moment, I'd like to know how you solve for this on a more global scale...  

Thanks again for a great course!

**Comment by dahlsailrunner** [comment]
Glad you got it figured out!  For many projects (and I discovered the issue with line endings after the course), the solution for me has been to include a `.gitattributes` file with the following content:
```
###############################################################################
# Set default behavior to automatically normalize line endings.
###############################################################################
* text=false
*.sh text eol=lf
```
This makes shell scripts (which usually target *nix) end in a line-feed character only.  The `* text=false` line says that git should leave existing line endings alone, but that didn't fully resolve the issue for me as different people committed code, etc.  We haven't had any issues since using the `.sh` line.

Hope this helps, and once again glad you liked the course.  :)
